/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxFileCaptureReceipt } from './sandbox-file-capture-receipt';

export interface SandboxFileCaptureObservation {
    'status': SandboxFileCaptureObservationStatusEnum;
    'receipt'?: SandboxFileCaptureReceipt;
}

export const SandboxFileCaptureObservationStatusEnum = {
    ABSENT: 'absent',
    PENDING: 'pending',
    COMPLETE: 'complete',
    RETIRED: 'retired',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type SandboxFileCaptureObservationStatusEnum = typeof SandboxFileCaptureObservationStatusEnum[keyof typeof SandboxFileCaptureObservationStatusEnum];


