/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SandboxFileCaptureDeleteReceipt {
    /**
     * Null when the operation was retired before a source was selected.
     */
    'captureId': string | null;
    'outcome': SandboxFileCaptureDeleteReceiptOutcomeEnum;
}

export const SandboxFileCaptureDeleteReceiptOutcomeEnum = {
    DELETED: 'deleted',
    ALREADY_ABSENT: 'already_absent',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type SandboxFileCaptureDeleteReceiptOutcomeEnum = typeof SandboxFileCaptureDeleteReceiptOutcomeEnum[keyof typeof SandboxFileCaptureDeleteReceiptOutcomeEnum];


