/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxRendererProcessIdentity } from './sandbox-renderer-process-identity';

export interface SandboxGenerationStopPurpose {
    'kind': SandboxGenerationStopPurposeKindEnum;
    'sessionId'?: string;
    'nonce'?: string;
    'rendererProcessIdentity'?: SandboxRendererProcessIdentity;
}

export const SandboxGenerationStopPurposeKindEnum = {
    WORKING_COPY_CAPTURE: 'working_copy_capture',
    DOCUMENT_RENDERER_QUIESCENCE: 'document_renderer_quiescence',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type SandboxGenerationStopPurposeKindEnum = typeof SandboxGenerationStopPurposeKindEnum[keyof typeof SandboxGenerationStopPurposeKindEnum];
