/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SandboxExecutionSource {
    /**
     * Exact Daytona sandbox identity.
     */
    'providerResourceId': string;
    'expectedProfile': SandboxExecutionSourceExpectedProfileEnum;
    'expectedRuntimeKind': SandboxExecutionSourceExpectedRuntimeKindEnum;
}

export const SandboxExecutionSourceExpectedProfileEnum = {
    MANAGED_CONTAINER: 'managed-container',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type SandboxExecutionSourceExpectedProfileEnum = typeof SandboxExecutionSourceExpectedProfileEnum[keyof typeof SandboxExecutionSourceExpectedProfileEnum];
export const SandboxExecutionSourceExpectedRuntimeKindEnum = {
    FULL_IMAGE_RUNTIME_PACK: 'full_image_runtime_pack',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type SandboxExecutionSourceExpectedRuntimeKindEnum = typeof SandboxExecutionSourceExpectedRuntimeKindEnum[keyof typeof SandboxExecutionSourceExpectedRuntimeKindEnum];
