/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxExecutionGeneration } from './sandbox-execution-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxFileCaptureComponent } from './sandbox-file-capture-component';

export interface SandboxFileCaptureReceipt {
    /**
     * Stable caller idempotency key. Reusing it never selects a new source generation.
     */
    'operationId': string;
    /**
     * Canonical regular-file path within /workspace/work or /workspace/outputs.
     */
    'path': string;
    'contract': SandboxFileCaptureReceiptContractEnum;
    'captureId': string;
    'organizationId': string;
    'sandboxId': string;
    'generation': SandboxExecutionGeneration;
    /**
     * Measured native implementation identity; does not certify a Product runtime.
     */
    'component': SandboxFileCaptureComponent;
    'totalByteLength': number;
    'sha256': string;
    'capturedAt': Date;
}

export const SandboxFileCaptureReceiptContractEnum = {
    DAYTONA_SANDBOX_FILE_CAPTURE_V1: 'daytona.sandbox-file-capture/v1',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type SandboxFileCaptureReceiptContractEnum = typeof SandboxFileCaptureReceiptContractEnum[keyof typeof SandboxFileCaptureReceiptContractEnum];


