/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SandboxFileCaptureRequest {
    /**
     * Stable caller idempotency key. Reusing it never selects a new source generation.
     */
    'operationId': string;
    /**
     * Canonical regular-file path within /workspace/work or /workspace/outputs.
     */
    'path': string;
}

