/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SandboxTerminalGeneration {
    'containerId': string;
    /**
     * Exact provider timestamp; preserve its original fractional precision.
     */
    'containerCreatedAt': string;
    /**
     * Exact provider timestamp; preserve its original fractional precision.
     */
    'executionStartedAt': string;
    'restartCount': number;
    /**
     * Exact provider timestamp; preserve its original fractional precision.
     */
    'executionFinishedAt': string;
    'exitCode': number;
    'oomKilled': boolean;
}
