/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SandboxFileCaptureObserveRequest {
    'operationId': string;
    /**
     * Optional assertion of the originally admitted path; observation does not access the live file.
     */
    'path'?: string;
}

