/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCopyCaptureBinding } from './working-copy-capture-binding';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCopyCaptureSelector } from './working-copy-capture-selector';

export interface StoppedWorkingCopyDirectoryRosterRequest {
    'anchor': WorkingCopyCaptureBinding;
    'selector': WorkingCopyCaptureSelector;
    'maximumDepth': number;
    'maximumEntries': number;
    'maximumFileBytes': number;
    'maximumAggregateBytes': number;
}
