/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxTerminalGeneration } from './sandbox-terminal-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { StoppedWorkingCopyDirectoryRosterEntry } from './stopped-working-copy-directory-roster-entry';
// May contain unused imports in some cases
// @ts-ignore
import type { StoppedWorkingCopyDirectoryRosterRequest } from './stopped-working-copy-directory-roster-request';

export interface StoppedWorkingCopyDirectoryRosterReceipt {
    'request': StoppedWorkingCopyDirectoryRosterRequest;
    'terminalGeneration': SandboxTerminalGeneration;
    'entries': Array<StoppedWorkingCopyDirectoryRosterEntry>;
    'rosterDigest': string;
    'observedAt': Date;
}
