/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StoppedWorkingCopyDirectoryRosterEntry {
    'zoneRelativePath': string;
    'name': string;
    'kind': StoppedWorkingCopyDirectoryRosterEntryKindEnum;
    'size': number;
    'mode': string | null;
    'sha256': string | null;
}

export const StoppedWorkingCopyDirectoryRosterEntryKindEnum = {
    REGULAR_FILE: 'regular_file',
    DIRECTORY: 'directory',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type StoppedWorkingCopyDirectoryRosterEntryKindEnum = typeof StoppedWorkingCopyDirectoryRosterEntryKindEnum[keyof typeof StoppedWorkingCopyDirectoryRosterEntryKindEnum];
