/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxTerminalGeneration } from './sandbox-terminal-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { StopSandboxGenerationRequest } from './stop-sandbox-generation-request';

export interface StoppedSandboxGenerationReceipt {
    'version': StoppedSandboxGenerationReceiptVersionEnum;
    'kind': StoppedSandboxGenerationReceiptKindEnum;
    'request': StopSandboxGenerationRequest;
    'receiptRef': string;
    'receiptDigest': string;
    'terminalGeneration': SandboxTerminalGeneration;
    'stoppedAt': Date;
}

export const StoppedSandboxGenerationReceiptVersionEnum = {
    NUMBER_1: 1,
    NUMBER_unknown_default_open_api: 11184809,
} as const;

export type StoppedSandboxGenerationReceiptVersionEnum = typeof StoppedSandboxGenerationReceiptVersionEnum[keyof typeof StoppedSandboxGenerationReceiptVersionEnum];
export const StoppedSandboxGenerationReceiptKindEnum = {
    AGENT_WORKSPACE_STOPPED_GENERATION_RECEIPT: 'agent_workspace_stopped_generation_receipt',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type StoppedSandboxGenerationReceiptKindEnum = typeof StoppedSandboxGenerationReceiptKindEnum[keyof typeof StoppedSandboxGenerationReceiptKindEnum];


