/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxExecutionGeneration } from './sandbox-execution-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxExecutionOwner } from './sandbox-execution-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxExecutionSource } from './sandbox-execution-source';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxGenerationFence } from './sandbox-generation-fence';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxGenerationStopPurpose } from './sandbox-generation-stop-purpose';

export interface StopSandboxGenerationRequest {
    'source': SandboxExecutionSource;
    'owner': SandboxExecutionOwner;
    'fence': SandboxGenerationFence;
    'operationId': string;
    'requestFingerprint': string;
    'expectedGeneration': SandboxExecutionGeneration;
    'purpose': SandboxGenerationStopPurpose;
}
