/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StoppedWorkingCopyWorkingTreeEntry {
    'name': string;
    'mode': string | null;
    'sha256': string | null;
    'kind': StoppedWorkingCopyWorkingTreeEntryKindEnum;
    /**
     * Lexical symlink target; never resolved by roster capture.
     */
    'linkTarget'?: string;
    'excludedKind'?: StoppedWorkingCopyWorkingTreeEntryExcludedKindEnum;
    'zoneRelativePath': string;
    'size': number;
    'byteOffset'?: number;
}

export const StoppedWorkingCopyWorkingTreeEntryKindEnum = {
    REGULAR_FILE: 'regular_file',
    DIRECTORY: 'directory',
    SYMLINK: 'symlink',
    EXCLUDED: 'excluded',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type StoppedWorkingCopyWorkingTreeEntryKindEnum = typeof StoppedWorkingCopyWorkingTreeEntryKindEnum[keyof typeof StoppedWorkingCopyWorkingTreeEntryKindEnum];
export const StoppedWorkingCopyWorkingTreeEntryExcludedKindEnum = {
    FIFO: 'fifo',
    CHARACTER_DEVICE: 'character_device',
    BLOCK_DEVICE: 'block_device',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type StoppedWorkingCopyWorkingTreeEntryExcludedKindEnum = typeof StoppedWorkingCopyWorkingTreeEntryExcludedKindEnum[keyof typeof StoppedWorkingCopyWorkingTreeEntryExcludedKindEnum];
