/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCopyCaptureBinding } from './working-copy-capture-binding';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCopyCaptureIdentity } from './working-copy-capture-identity';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCopyCaptureReceipt } from './working-copy-capture-receipt';

export interface WorkingCopyCaptureObservation {
    'status': WorkingCopyCaptureObservationStatusEnum;
    'binding'?: WorkingCopyCaptureBinding;
    'identity'?: WorkingCopyCaptureIdentity;
    'receipt'?: WorkingCopyCaptureReceipt;
}

export const WorkingCopyCaptureObservationStatusEnum = {
    ABSENT: 'absent',
    PARTIAL: 'partial',
    COMPLETE: 'complete',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingCopyCaptureObservationStatusEnum = typeof WorkingCopyCaptureObservationStatusEnum[keyof typeof WorkingCopyCaptureObservationStatusEnum];
