/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingTreeInventoryRequest } from './working-tree-inventory-request';

export interface WorkingTreeInventoryDeletionReceipt {
    'request': WorkingTreeInventoryRequest;
    'providerResourceId': string;
    'status': WorkingTreeInventoryDeletionReceiptStatusEnum;
}

export const WorkingTreeInventoryDeletionReceiptStatusEnum = {
    ABSENT: 'absent',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingTreeInventoryDeletionReceiptStatusEnum = typeof WorkingTreeInventoryDeletionReceiptStatusEnum[keyof typeof WorkingTreeInventoryDeletionReceiptStatusEnum];
