/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkingTreeInventoryCapability {
    'semanticZoneRef': WorkingTreeInventoryCapabilitySemanticZoneRefEnum;
    'maximumDepth': number;
    'maximumFileBytes': number;
    'maximumAggregateBytes': number;
    'maximumReadBytes': number;
    'contract': WorkingTreeInventoryCapabilityContractEnum;
    'maximumPageEntries': number;
    'maximumPageBytes': number;
    'maximumIndexBytes': number;
}

export const WorkingTreeInventoryCapabilitySemanticZoneRefEnum = {
    AMBIT_WORKSPACE_ZONE_USER_FILES_1: 'ambit.workspace-zone/user-files@1',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingTreeInventoryCapabilitySemanticZoneRefEnum = typeof WorkingTreeInventoryCapabilitySemanticZoneRefEnum[keyof typeof WorkingTreeInventoryCapabilitySemanticZoneRefEnum];
export const WorkingTreeInventoryCapabilityContractEnum = {
    AMBIT_WORKING_COPY_STOPPED_WORKING_TREE_INVENTORY_V1: 'ambit.working-copy-stopped-working-tree-inventory/v1',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingTreeInventoryCapabilityContractEnum = typeof WorkingTreeInventoryCapabilityContractEnum[keyof typeof WorkingTreeInventoryCapabilityContractEnum];
