/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCopyCaptureAuthorityArtifact } from './working-copy-capture-authority-artifact';

export interface WorkingCopyCaptureAuthority {
    'authorityRef': string;
    'lineageRef': string;
    'roleRef': WorkingCopyCaptureAuthorityRoleRefEnum;
    'protocol': WorkingCopyCaptureAuthorityArtifact;
    'helper': WorkingCopyCaptureAuthorityArtifact;
}

export const WorkingCopyCaptureAuthorityRoleRefEnum = {
    AMBIT_RUNTIME_COMPONENT_WORKING_COPY_CAPTURE_2: 'ambit.runtime-component/working-copy-capture@2',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingCopyCaptureAuthorityRoleRefEnum = typeof WorkingCopyCaptureAuthorityRoleRefEnum[keyof typeof WorkingCopyCaptureAuthorityRoleRefEnum];
