/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkingCopyFileSnapshotCapability {
    'contract': WorkingCopyFileSnapshotCapabilityContractEnum;
    'maximumBytes': number;
}

export const WorkingCopyFileSnapshotCapabilityContractEnum = {
    AMBIT_WORKING_COPY_FILE_SNAPSHOT_V1: 'ambit.working-copy-file-snapshot/v1',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingCopyFileSnapshotCapabilityContractEnum = typeof WorkingCopyFileSnapshotCapabilityContractEnum[keyof typeof WorkingCopyFileSnapshotCapabilityContractEnum];
