/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxTerminalGeneration } from './sandbox-terminal-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingTreeInventoryBytePack } from './working-tree-inventory-byte-pack';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingTreeInventoryPageDescriptor } from './working-tree-inventory-page-descriptor';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingTreeInventoryRequest } from './working-tree-inventory-request';

export interface WorkingTreeInventoryReceipt {
    'request': WorkingTreeInventoryRequest;
    'providerResourceId': string;
    'terminalGeneration': SandboxTerminalGeneration;
    'pages': Array<WorkingTreeInventoryPageDescriptor>;
    'entryCount': number;
    'aggregateBytes': number;
    'bytePack': WorkingTreeInventoryBytePack;
    'inventoryDigest': string;
    'observedAt': Date;
}
