/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkingCopyCaptureSelector {
    'semanticZoneRef': WorkingCopyCaptureSelectorSemanticZoneRefEnum;
    /**
     * Bounded canonical path relative to the admitted semantic zone.
     */
    'zoneRelativePath': string;
}

export const WorkingCopyCaptureSelectorSemanticZoneRefEnum = {
    AMBIT_WORKSPACE_ZONE_WORK_1: 'ambit.workspace-zone/work@1',
    AMBIT_WORKSPACE_ZONE_OUTPUTS_1: 'ambit.workspace-zone/outputs@1',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingCopyCaptureSelectorSemanticZoneRefEnum = typeof WorkingCopyCaptureSelectorSemanticZoneRefEnum[keyof typeof WorkingCopyCaptureSelectorSemanticZoneRefEnum];


