/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxExecutionOwner } from './sandbox-execution-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxExecutionSource } from './sandbox-execution-source';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxGenerationStopAuthority } from './sandbox-generation-stop-authority';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCopyCaptureAuthority } from './working-copy-capture-authority';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCopyCaptureReceipt } from './working-copy-capture-receipt';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCopyCaptureSelector } from './working-copy-capture-selector';

export interface WorkingCopyCaptureExistsResponse {
    'providerName': string;
    'requestFingerprint': string;
    'authority': WorkingCopyCaptureAuthority;
    'source': SandboxExecutionSource;
    'owner': SandboxExecutionOwner;
    'stopAuthority': SandboxGenerationStopAuthority;
    'selector': WorkingCopyCaptureSelector;
    'providerResourceId': string;
    'status': WorkingCopyCaptureExistsResponseStatusEnum;
    'exists': boolean;
    'receipt'?: WorkingCopyCaptureReceipt;
}

export const WorkingCopyCaptureExistsResponseStatusEnum = {
    ABSENT: 'absent',
    PARTIAL: 'partial',
    COMPLETE: 'complete',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingCopyCaptureExistsResponseStatusEnum = typeof WorkingCopyCaptureExistsResponseStatusEnum[keyof typeof WorkingCopyCaptureExistsResponseStatusEnum];
