/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkingCopyFileSnapshotCapability {
    'contract': WorkingCopyFileSnapshotCapabilityContractEnum;
    'maximumBytes': number;
}

export const WorkingCopyFileSnapshotCapabilityContractEnum = {
    AMBIT_WORKING_COPY_FILE_SNAPSHOT_V1: 'ambit.working-copy-file-snapshot/v1',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingCopyFileSnapshotCapabilityContractEnum = typeof WorkingCopyFileSnapshotCapabilityContractEnum[keyof typeof WorkingCopyFileSnapshotCapabilityContractEnum];
