/*
 * Copyright 2025 Daytona Platforms Inc.
 * SPDX-License-Identifier: AGPL-3.0
 */

export enum AuditAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  LOGIN = 'login',
  SET_DEFAULT = 'set_default',
  UPDATE_ACCESS = 'update_access',
  UPDATE_QUOTA = 'update_quota',
  CREATE_REGION_QUOTA = 'create_region_quota',
  UPDATE_REGION_QUOTA = 'update_region_quota',
  DELETE_REGION_QUOTA = 'delete_region_quota',
  SUSPEND = 'suspend',
  UNSUSPEND = 'unsuspend',
  ACCEPT = 'accept',
  DECLINE = 'decline',
  LINK_ACCOUNT = 'link_account',
  UNLINK_ACCOUNT = 'unlink_account',
  LEAVE_ORGANIZATION = 'leave_organization',
  REGENERATE_KEY_PAIR = 'regenerate_key_pair',
  UPDATE_SCHEDULING = 'update_scheduling',
  UPDATE_DRAINING = 'update_draining',
  START = 'start',
  STOP = 'stop',
  RESIZE = 'resize',
  REPLACE_LABELS = 'replace_labels',
  CREATE_BACKUP = 'create_backup',
  UPDATE_PUBLIC_STATUS = 'update_public_status',
  SET_AUTO_STOP_INTERVAL = 'set_auto_stop_interval',
  SET_AUTO_PAUSE_INTERVAL = 'set_auto_pause_interval',
  SET_AUTO_ARCHIVE_INTERVAL = 'set_auto_archive_interval',
  SET_AUTO_DELETE_INTERVAL = 'set_auto_delete_interval',
  SET_TTL = 'set_ttl',
  ARCHIVE = 'archive',
  SNAPSHOT = 'snapshot',
  FORK = 'fork',
  PAUSE = 'pause',
  GET_PORT_PREVIEW_URL = 'get_port_preview_url',
  SET_GENERAL_STATUS = 'set_general_status',
  ACTIVATE = 'activate',
  DEACTIVATE = 'deactivate',
  UPDATE_NETWORK_SETTINGS = 'update_network_settings',
  UPDATE_SECRETS = 'update_secrets',
  SEND_WEBHOOK_MESSAGE = 'send_webhook_message',
  INITIALIZE_WEBHOOKS = 'initialize_webhooks',
  UPDATE_SANDBOX_DEFAULT_LIMITED_NETWORK_EGRESS = 'update_sandbox_default_limited_network_egress',
  UPDATE_PREVIEW_WARNING = 'update_preview_warning',
  UPDATE_OTEL_CONFIG = 'update_otel_config',
  DELETE_OTEL_CONFIG = 'delete_otel_config',
  CREATE_SSH_ACCESS = 'create_ssh_access',
  REVOKE_SSH_ACCESS = 'revoke_ssh_access',
  RECOVER = 'recover',
  REGENERATE_PROXY_API_KEY = 'regenerate_proxy_api_key',
  REGENERATE_SSH_GATEWAY_API_KEY = 'regenerate_ssh_gateway_api_key',
  REGENERATE_SNAPSHOT_MANAGER_CREDENTIALS = 'regenerate_snapshot_manager_credentials',
  AUTO_STOP = 'auto_stop',
  AUTO_ARCHIVE = 'auto_archive',
  AUTO_DELETE = 'auto_delete',
  AUTO_DESTROY = 'auto_destroy',
}
