# Copyright 2026 Ambit
# SPDX-License-Identifier: AGPL-3.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: daytona-minio
  namespace: daytona-state
  labels:
    app.kubernetes.io/name: daytona
    app.kubernetes.io/component: object-storage
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daytona-harbor
  namespace: daytona-state
  labels:
    app.kubernetes.io/name: daytona
    app.kubernetes.io/component: harbor
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daytona-harbor-cloud
  namespace: daytona-state
  labels:
    app.kubernetes.io/name: daytona
    app.kubernetes.io/component: harbor
  annotations:
    iam.gke.io/gcp-service-account: ambit-daytona-runtime@mwcc-infrastructure.iam.gserviceaccount.com
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daytona-harbor-secrets
  namespace: daytona-state
  labels:
    app.kubernetes.io/name: daytona
    app.kubernetes.io/component: harbor-secret-sync
automountServiceAccountToken: false
