/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopReceipt } from './generationstop-receipt';
// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopStopRequest } from './generationstop-stop-request';

export interface GenerationstopObservation {
    'receipt'?: GenerationstopReceipt;
    'request'?: GenerationstopStopRequest;
    'status': string;
}

