/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopFence } from './generationstop-fence';
// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopOwner } from './generationstop-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopSource } from './generationstop-source';

export interface GenerationstopGenerationObservationRequest {
    'fence': GenerationstopFence;
    'owner': GenerationstopOwner;
    'source': GenerationstopSource;
}
