/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopExpectedGeneration } from './generationstop-expected-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { SpecialistrenderProcessIdentity } from './specialistrender-process-identity';

export interface SpecialistrenderLaunchObservation {
    'capDrop': Array<string>;
    'command': Array<string>;
    'containerId': string;
    'containerName': string;
    'effectiveCapabilities': string;
    'environmentDigest': string;
    'executableDigest': string;
    'executablePath': string;
    'hostPid': number;
    'imageId': string;
    'memoryBytes': number;
    'mountCount'?: number;
    'mountNamespace': string;
    'nanoCpus': number;
    'networkMode': string;
    'noNewPrivileges': boolean;
    'observedAt': string;
    'parentGeneration': GenerationstopExpectedGeneration;
    'parentMountNamespace': string;
    'parentProcessNamespace': string;
    'pidsLimit': number;
    'processCount': number;
    'processIdentity': SpecialistrenderProcessIdentity;
    'processNamespace': string;
    'readonlyRootfs': boolean;
    'roleRef': string;
    'runtime': string;
    'runtimeStatusDigest': string;
    'seccompDigest'?: string;
    'seccompKernelMode': number;
    'seccompMode': string;
    'shmSize'?: number;
    'tmpfs': { [key: string]: string; };
    'user': string;
}
