/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopExpectedGeneration } from './generationstop-expected-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopFence } from './generationstop-fence';
// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopProviderOwner } from './generationstop-provider-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopSource } from './generationstop-source';
// May contain unused imports in some cases
// @ts-ignore
import type { SpecialistrenderImagePin } from './specialistrender-image-pin';
// May contain unused imports in some cases
// @ts-ignore
import type { SpecialistrenderPin } from './specialistrender-pin';

export interface SpecialistrenderRequest {
    'artifactRenderJobRef': string;
    'composition': SpecialistrenderPin;
    'executable': string;
    'executor': SpecialistrenderPin;
    'expectedParentGeneration': GenerationstopExpectedGeneration;
    'fence': GenerationstopFence;
    'image': SpecialistrenderImagePin;
    'interface': SpecialistrenderPin;
    'operationId': string;
    'owner': GenerationstopProviderOwner;
    'providerPolicy': SpecialistrenderPin;
    'requestBytes': number;
    'requestChunkCount': number;
    'requestFingerprint': string;
    'requestSha256': string;
    'schema': string;
    'source': GenerationstopSource;
    'sourceBytes': number;
    'sourceChunkCount': number;
    'sourceSha256': string;
}
