/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SpecialistrenderLaunchObservation } from './specialistrender-launch-observation';
// May contain unused imports in some cases
// @ts-ignore
import type { SpecialistrenderOutputFile } from './specialistrender-output-file';
// May contain unused imports in some cases
// @ts-ignore
import type { SpecialistrenderQuiescenceReceipt } from './specialistrender-quiescence-receipt';
// May contain unused imports in some cases
// @ts-ignore
import type { SpecialistrenderRequest } from './specialistrender-request';

export interface SpecialistrenderReceipt {
    'completedAt': string;
    'files': Array<SpecialistrenderOutputFile>;
    'helperExitCode': number;
    'launch': SpecialistrenderLaunchObservation;
    'nonce': string;
    'outcome': string;
    'quiescence': SpecialistrenderQuiescenceReceipt;
    'readyDigest': string;
    'receiptDigest': string;
    'request': SpecialistrenderRequest;
    'schema': string;
    'startedAt': string;
    'terminalDigest': string;
    'terminalKind': string;
    'terminalOutcome': string;
    'totalOutputBytes': number;
}
