/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateSandboxSecretsDTO {
    /**
     * Env is the sandbox\'s full desired secret env: env var names mapped to secret placeholder values. Replace semantics — placeholder-valued env vars not present in the map are unset for newly spawned processes.
     */
    'env'?: { [key: string]: string; };
}

