/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopStopAuthority } from './generationstop-stop-authority';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyCaptureAuthority } from './workingcopy-capture-authority';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyCaptureOwner } from './workingcopy-capture-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyCaptureSelector } from './workingcopy-capture-selector';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopySourceAddress } from './workingcopy-source-address';

export interface WorkingcopyCaptureReadResponse {
    'authority': WorkingcopyCaptureAuthority;
    'byteLength'?: number;
    'bytesBase64'?: string;
    'eof'?: boolean;
    'offset': number;
    'owner': WorkingcopyCaptureOwner;
    'providerName': string;
    'providerResourceId': string;
    'providerSha256Digest': string;
    'requestFingerprint': string;
    'selector': WorkingcopyCaptureSelector;
    'source': WorkingcopySourceAddress;
    'stopAuthority': GenerationstopStopAuthority;
    'totalByteLength': number;
}
