/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { WorkingcopyCaptureAuthority } from './workingcopy-capture-authority';
import type { GenerationstopSource } from './generationstop-source';
import type { GenerationstopOwner } from './generationstop-owner';
import type { GenerationstopFence } from './generationstop-fence';

export interface WorkingcopyCaptureCapabilitiesRequest {
    'authority': WorkingcopyCaptureAuthority;
    'source': GenerationstopSource;
    'owner': GenerationstopOwner;
    'fence': GenerationstopFence;
}
