/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyCaptureBinding } from './workingcopy-capture-binding';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyCaptureIdentity } from './workingcopy-capture-identity';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyCaptureReceipt } from './workingcopy-capture-receipt';

export interface WorkingcopyCaptureObservation {
    'binding'?: WorkingcopyCaptureBinding;
    'identity'?: WorkingcopyCaptureIdentity;
    'receipt'?: WorkingcopyCaptureReceipt;
    'status': string;
}

