/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { WorkingcopyCaptureGenerationBinding } from './workingcopy-capture-generation-binding';

export interface WorkingcopyWorkingTreeInventoryRequest {
    'generation': WorkingcopyCaptureGenerationBinding;
    'excludedPaths': Array<string>;
    'maximumDepth': number;
    'maximumFileBytes': number;
    'maximumAggregateBytes': number;
    'maximumPageEntries': number;
    'maximumPageBytes': number;
}
