/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkingcopySandboxFileDeleteReceipt {
    'captureId': string | null;
    'outcome': WorkingcopySandboxFileDeleteReceiptOutcomeEnum;
}

export const WorkingcopySandboxFileDeleteReceiptOutcomeEnum = {
    DELETED: 'deleted',
    ALREADY_ABSENT: 'already_absent',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingcopySandboxFileDeleteReceiptOutcomeEnum = typeof WorkingcopySandboxFileDeleteReceiptOutcomeEnum[keyof typeof WorkingcopySandboxFileDeleteReceiptOutcomeEnum];
