/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopExpectedGeneration } from './generationstop-expected-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyCaptureComponent } from './workingcopy-capture-component';

export interface WorkingcopySandboxFileReceipt {
    'captureId': string;
    'capturedAt': string;
    'component': WorkingcopyCaptureComponent;
    'contract': string;
    'generation': GenerationstopExpectedGeneration;
    'operationId': string;
    'organizationId': string;
    'path': string;
    'sandboxId': string;
    'sha256': string;
    'totalByteLength': number;
}
