/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopTerminalGeneration } from './generationstop-terminal-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyStoppedDirectoryRosterEntry } from './workingcopy-stopped-directory-roster-entry';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyStoppedDirectoryRosterRequest } from './workingcopy-stopped-directory-roster-request';

export interface WorkingcopyStoppedDirectoryRosterReceipt {
    'entries': Array<WorkingcopyStoppedDirectoryRosterEntry>;
    'observedAt': string;
    'request': WorkingcopyStoppedDirectoryRosterRequest;
    'rosterDigest': string;
    'terminalGeneration': GenerationstopTerminalGeneration;
}
