/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyCaptureBinding } from './workingcopy-capture-binding';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyCaptureSelector } from './workingcopy-capture-selector';

export interface WorkingcopyStoppedDirectoryRosterRequest {
    'anchor': WorkingcopyCaptureBinding;
    'maximumAggregateBytes': number;
    'maximumDepth': number;
    'maximumEntries': number;
    'maximumFileBytes': number;
    'selector': WorkingcopyCaptureSelector;
}
