/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopySandboxFileReceipt } from './workingcopy-sandbox-file-receipt';

export interface WorkingcopySandboxFileObservation {
    'receipt'?: WorkingcopySandboxFileReceipt;
    'status': WorkingcopySandboxFileObservationStatusEnum;
}

export const WorkingcopySandboxFileObservationStatusEnum = {
    ABSENT: 'absent',
    PENDING: 'pending',
    COMPLETE: 'complete',
    RETIRED: 'retired',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingcopySandboxFileObservationStatusEnum = typeof WorkingcopySandboxFileObservationStatusEnum[keyof typeof WorkingcopySandboxFileObservationStatusEnum];
