/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { WorkingcopyWorkingTreeInventoryRequest } from './workingcopy-working-tree-inventory-request';

export interface WorkingcopyWorkingTreeInventoryDeletionReceipt {
    'request': WorkingcopyWorkingTreeInventoryRequest;
    'providerResourceId': string;
    'status': 'absent';
}
