/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { WorkingcopyCaptureAuthority } from './workingcopy-capture-authority';
import type { WorkingcopyStoppedWorkingTreeCapability } from './workingcopy-stopped-working-tree-capability';

export interface WorkingcopyCaptureCapabilities {
    'authority': WorkingcopyCaptureAuthority;
    'stoppedWorkingTree': WorkingcopyStoppedWorkingTreeCapability;
}
