/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkingcopyWorkingTreeInventoryPageDescriptor {
    'byteLength': number;
    'entryCount': number;
    'firstPath': string;
    'lastPath': string;
    'pageIndex': number;
    'sha256': string;
}
