/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyWorkingTreeInventoryBytePart } from './workingcopy-working-tree-inventory-byte-part';

export interface WorkingcopyWorkingTreeInventoryBytePack {
    'byteLength': number;
    'parts': Array<WorkingcopyWorkingTreeInventoryBytePart>;
    'sha256': string;
}
