/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopySandboxFileReceipt } from './workingcopy-sandbox-file-receipt';

export interface WorkingcopySandboxFileReadRequest {
    'maximumBytes': number;
    'offset': number;
    'receipt': WorkingcopySandboxFileReceipt;
}
