/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyWorkingTreeInventoryRequest } from './workingcopy-working-tree-inventory-request';

export interface WorkingcopyWorkingTreeInventoryPageRequest {
    'pageIndex': number;
    'providerResourceId': string;
    'request': WorkingcopyWorkingTreeInventoryRequest;
}
