/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyWorkingTreeInventoryRequest } from './workingcopy-working-tree-inventory-request';

export interface WorkingcopyWorkingTreeInventoryDeletionReceipt {
    'providerResourceId': string;
    'request': WorkingcopyWorkingTreeInventoryRequest;
    'status': WorkingcopyWorkingTreeInventoryDeletionReceiptStatusEnum;
}

export const WorkingcopyWorkingTreeInventoryDeletionReceiptStatusEnum = {
    ABSENT: 'absent',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingcopyWorkingTreeInventoryDeletionReceiptStatusEnum = typeof WorkingcopyWorkingTreeInventoryDeletionReceiptStatusEnum[keyof typeof WorkingcopyWorkingTreeInventoryDeletionReceiptStatusEnum];
