/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkingcopyWorkingTreeInventoryCapability {
    'contract': string;
    'semanticZoneRef': string;
    'maximumDepth': number;
    'maximumFileBytes': number;
    'maximumAggregateBytes': number;
    'maximumPageEntries': number;
    'maximumPageBytes': number;
    'maximumIndexBytes': number;
    'maximumReadBytes': number;
}
