/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GenerationstopTerminalGeneration } from './generationstop-terminal-generation';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyWorkingTreeInventoryBytePack } from './workingcopy-working-tree-inventory-byte-pack';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyWorkingTreeInventoryPageDescriptor } from './workingcopy-working-tree-inventory-page-descriptor';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingcopyWorkingTreeInventoryRequest } from './workingcopy-working-tree-inventory-request';

export interface WorkingcopyWorkingTreeInventoryReceipt {
    'aggregateBytes': number;
    'bytePack': WorkingcopyWorkingTreeInventoryBytePack;
    'entryCount': number;
    'inventoryDigest': string;
    'observedAt': string;
    'pages': Array<WorkingcopyWorkingTreeInventoryPageDescriptor>;
    'providerResourceId': string;
    'request': WorkingcopyWorkingTreeInventoryRequest;
    'terminalGeneration': GenerationstopTerminalGeneration;
}
