/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Runner API
 * Daytona Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WorkingcopyStoppedWorkingTreeEntry {
    'byteOffset'?: number;
    'excludedKind'?: WorkingcopyStoppedWorkingTreeEntryExcludedKindEnum;
    'kind': WorkingcopyStoppedWorkingTreeEntryKindEnum;
    'linkTarget'?: string;
    'mode': string | null;
    'name': string;
    'sha256': string | null;
    'size': number;
    'zoneRelativePath': string;
}

export const WorkingcopyStoppedWorkingTreeEntryExcludedKindEnum = {
    FIFO: 'fifo',
    CHARACTER_DEVICE: 'character_device',
    BLOCK_DEVICE: 'block_device',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingcopyStoppedWorkingTreeEntryExcludedKindEnum = typeof WorkingcopyStoppedWorkingTreeEntryExcludedKindEnum[keyof typeof WorkingcopyStoppedWorkingTreeEntryExcludedKindEnum];
export const WorkingcopyStoppedWorkingTreeEntryKindEnum = {
    REGULAR_FILE: 'regular_file',
    DIRECTORY: 'directory',
    SYMLINK: 'symlink',
    EXCLUDED: 'excluded',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type WorkingcopyStoppedWorkingTreeEntryKindEnum = typeof WorkingcopyStoppedWorkingTreeEntryKindEnum[keyof typeof WorkingcopyStoppedWorkingTreeEntryKindEnum];
