// Copyright 2025 Daytona Platforms Inc.
// SPDX-License-Identifier: AGPL-3.0

package c18preactivation

import (
	"bytes"
	_ "embed"
	"errors"
	"fmt"

	"github.com/daytonaio/runner/pkg/generationstop"
	"github.com/daytonaio/runner/pkg/specialistrender"
)

const (
	candidatePinRosterContract       = "C18PreactivationCandidatePinRoster@1"
	candidatePinRosterRegistryRef    = "ambit.renderer-registry/c18-specialist-candidates@2"
	candidatePinRosterRawDigest      = "sha256:925882c181c6de4fbd3dac8617102a0795d8ca1982a453fc6309f2ee1c2d6c10"
	candidatePinRosterSemanticDigest = "sha256:60e27ba6791ae078d17975b81d1661e5fc37f894e133988ea1635c4f058037e9"
)

// The source fixture is generated by the backend from its current candidate
// registry and embedded as the exact 2,487 canonical bytes with no framing.
//
//go:embed c18-preactivation-candidate-pin-roster.v1.json
var embeddedCandidatePinRosterBytes []byte

type candidatePinRosterV1 struct {
	CandidateRegistryRef string                  `json:"candidateRegistryRef"`
	Candidates           []candidatePinRosterRow `json:"candidates"`
	Contract             string                  `json:"contract"`
	Digest               string                  `json:"digest"`
}

type candidatePinRosterRow struct {
	CandidateDigest string `json:"candidateDigest"`
	CandidateRef    string `json:"candidateRef"`
}

var currentCandidatePins = mustLoadCandidatePinRoster()

func mustLoadCandidatePinRoster() candidatePinRosterV1 {
	roster, err := loadCandidatePinRoster(embeddedCandidatePinRosterBytes)
	if err != nil {
		panic(fmt.Sprintf("load embedded C18 candidate pin roster: %v", err))
	}
	return roster
}

func loadCandidatePinRoster(canonical []byte) (candidatePinRosterV1, error) {
	if len(canonical) != 2_487 || bytes.IndexByte(canonical, '\n') >= 0 ||
		bytes.IndexByte(canonical, '\r') >= 0 || sha256Digest(canonical) != candidatePinRosterRawDigest {
		return candidatePinRosterV1{}, errors.New("candidate pin roster differs from the generated canonical bytes")
	}
	var roster candidatePinRosterV1
	if err := generationstop.DecodeCanonicalJSON(canonical, &roster); err != nil {
		return candidatePinRosterV1{}, fmt.Errorf("decode candidate pin roster: %w", err)
	}
	if roster.Contract != candidatePinRosterContract ||
		roster.CandidateRegistryRef != candidatePinRosterRegistryRef ||
		roster.Digest != candidatePinRosterSemanticDigest || len(roster.Candidates) != 14 {
		return candidatePinRosterV1{}, errors.New("candidate pin roster identity is invalid")
	}
	if err := verifySealedDigest(roster, roster.Digest); err != nil {
		return candidatePinRosterV1{}, err
	}
	previous := ""
	for _, candidate := range roster.Candidates {
		if candidate.CandidateRef <= previous || !exactSHA256.MatchString(candidate.CandidateDigest) {
			return candidatePinRosterV1{}, errors.New("candidate pin roster rows are invalid or noncanonical")
		}
		if _, found := runtimePolicyForCandidate(candidate.CandidateRef); !found {
			return candidatePinRosterV1{}, errors.New("candidate pin roster is outside the runtime policy")
		}
		previous = candidate.CandidateRef
	}
	for _, policy := range runtimeRenderPolicy.Entries {
		candidateRef := candidateRefForRenderer(policy.RendererRef)
		if !candidateRosterContainsRef(roster, candidateRef) {
			return candidatePinRosterV1{}, errors.New("runtime policy candidate is absent from the pin roster")
		}
	}
	return roster, nil
}

func currentCandidatePin(pin specialistrender.Pin) bool {
	for _, candidate := range currentCandidatePins.Candidates {
		if candidate.CandidateRef == pin.Ref {
			return candidate.CandidateDigest == pin.Digest
		}
	}
	return false
}

func candidateRosterContainsRef(roster candidatePinRosterV1, ref string) bool {
	for _, candidate := range roster.Candidates {
		if candidate.CandidateRef == ref {
			return true
		}
	}
	return false
}
