// Copyright 2025 Daytona Platforms Inc.
// SPDX-License-Identifier: AGPL-3.0

package c18preactivation

import (
	"testing"

	"github.com/daytonaio/runner/pkg/specialistrender"
)

func TestCandidatePinRosterMatchesBackendGeneratedCanonicalVector(t *testing.T) {
	canonical := embeddedCandidatePinRosterBytes
	if len(canonical) != 2_487 || sha256Digest(canonical) != candidatePinRosterRawDigest {
		t.Fatal("candidate pin roster does not retain the exact backend-generated bytes")
	}
	if len(currentCandidatePins.Candidates) != 14 ||
		currentCandidatePins.Digest != candidatePinRosterSemanticDigest {
		t.Fatal("candidate pin roster lost its exact authority identity")
	}
	for _, candidate := range currentCandidatePins.Candidates {
		if !currentCandidatePin(specialistrender.Pin{Ref: candidate.CandidateRef, Digest: candidate.CandidateDigest}) {
			t.Fatalf("current candidate pin %s was not admitted", candidate.CandidateRef)
		}
		if currentCandidatePin(specialistrender.Pin{Ref: candidate.CandidateRef, Digest: "sha256:" + repeatHex("f")}) {
			t.Fatalf("forged candidate digest for %s was admitted", candidate.CandidateRef)
		}
	}
}
