// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package firewall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type firewallConnKey struct {
	_          structs.HostLayout
	RemoteIp   uint32
	RemotePort uint16
	LocalPort  uint16
}

type firewallDnsNameKey struct {
	_    structs.HostLayout
	Name [128]int8
}

type firewallOrigDst struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	Pad  uint16
}

type firewallProxyCfg struct {
	_         structs.HostLayout
	ProxyIp   uint32
	ProxyPort uint16
	Enforce   uint8
	Pad       uint8
}

// loadFirewall returns the embedded CollectionSpec for firewall.
func loadFirewall() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FirewallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load firewall: %w", err)
	}

	return spec, err
}

// loadFirewallObjects loads firewall and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*firewallObjects
//	*firewallPrograms
//	*firewallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFirewallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFirewall()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// firewallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallSpecs struct {
	firewallProgramSpecs
	firewallMapSpecs
	firewallVariableSpecs
}

// firewallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallProgramSpecs struct {
	FirewallConnect4     *ebpf.ProgramSpec `ebpf:"firewall_connect4"`
	FirewallDnsIngress   *ebpf.ProgramSpec `ebpf:"firewall_dns_ingress"`
	FirewallEgress       *ebpf.ProgramSpec `ebpf:"firewall_egress"`
	FirewallGetpeername4 *ebpf.ProgramSpec `ebpf:"firewall_getpeername4"`
}

// firewallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallMapSpecs struct {
	AllowedDomains   *ebpf.MapSpec `ebpf:"allowed_domains"`
	AllowedIps       *ebpf.MapSpec `ebpf:"allowed_ips"`
	AllowedWildcards *ebpf.MapSpec `ebpf:"allowed_wildcards"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	InboundConns     *ebpf.MapSpec `ebpf:"inbound_conns"`
	InternalDnsZones *ebpf.MapSpec `ebpf:"internal_dns_zones"`
	OrigDstMap       *ebpf.MapSpec `ebpf:"orig_dst_map"`
	ProxyConfig      *ebpf.MapSpec `ebpf:"proxy_config"`
	ReportedIps      *ebpf.MapSpec `ebpf:"reported_ips"`
}

// firewallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallVariableSpecs struct {
}

// firewallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallObjects struct {
	firewallPrograms
	firewallMaps
	firewallVariables
}

func (o *firewallObjects) Close() error {
	return _FirewallClose(
		&o.firewallPrograms,
		&o.firewallMaps,
	)
}

// firewallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallMaps struct {
	AllowedDomains   *ebpf.Map `ebpf:"allowed_domains"`
	AllowedIps       *ebpf.Map `ebpf:"allowed_ips"`
	AllowedWildcards *ebpf.Map `ebpf:"allowed_wildcards"`
	Events           *ebpf.Map `ebpf:"events"`
	InboundConns     *ebpf.Map `ebpf:"inbound_conns"`
	InternalDnsZones *ebpf.Map `ebpf:"internal_dns_zones"`
	OrigDstMap       *ebpf.Map `ebpf:"orig_dst_map"`
	ProxyConfig      *ebpf.Map `ebpf:"proxy_config"`
	ReportedIps      *ebpf.Map `ebpf:"reported_ips"`
}

func (m *firewallMaps) Close() error {
	return _FirewallClose(
		m.AllowedDomains,
		m.AllowedIps,
		m.AllowedWildcards,
		m.Events,
		m.InboundConns,
		m.InternalDnsZones,
		m.OrigDstMap,
		m.ProxyConfig,
		m.ReportedIps,
	)
}

// firewallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallVariables struct {
}

// firewallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFirewallObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallPrograms struct {
	FirewallConnect4     *ebpf.Program `ebpf:"firewall_connect4"`
	FirewallDnsIngress   *ebpf.Program `ebpf:"firewall_dns_ingress"`
	FirewallEgress       *ebpf.Program `ebpf:"firewall_egress"`
	FirewallGetpeername4 *ebpf.Program `ebpf:"firewall_getpeername4"`
}

func (p *firewallPrograms) Close() error {
	return _FirewallClose(
		p.FirewallConnect4,
		p.FirewallDnsIngress,
		p.FirewallEgress,
		p.FirewallGetpeername4,
	)
}

func _FirewallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed firewall_bpfel.o
var _FirewallBytes []byte
