// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package firewall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type firewallTcConnKey struct {
	_          structs.HostLayout
	RemoteIp   uint32
	RemotePort uint16
	LocalPort  uint16
}

type firewallTcDnsNameKey struct {
	_    structs.HostLayout
	Name [128]int8
}

type firewallTcProxyCfg struct {
	_         structs.HostLayout
	ProxyIp   uint32
	ProxyPort uint16
	Enforce   uint8
	Pad       uint8
}

// loadFirewallTc returns the embedded CollectionSpec for firewallTc.
func loadFirewallTc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FirewallTcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load firewallTc: %w", err)
	}

	return spec, err
}

// loadFirewallTcObjects loads firewallTc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*firewallTcObjects
//	*firewallTcPrograms
//	*firewallTcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFirewallTcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFirewallTc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// firewallTcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallTcSpecs struct {
	firewallTcProgramSpecs
	firewallTcMapSpecs
	firewallTcVariableSpecs
}

// firewallTcProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallTcProgramSpecs struct {
	FirewallTcDnsIngress *ebpf.ProgramSpec `ebpf:"firewall_tc_dns_ingress"`
	FirewallTcEgress     *ebpf.ProgramSpec `ebpf:"firewall_tc_egress"`
}

// firewallTcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallTcMapSpecs struct {
	AllowedDomains   *ebpf.MapSpec `ebpf:"allowed_domains"`
	AllowedIps       *ebpf.MapSpec `ebpf:"allowed_ips"`
	AllowedWildcards *ebpf.MapSpec `ebpf:"allowed_wildcards"`
	Events           *ebpf.MapSpec `ebpf:"events"`
	InboundConns     *ebpf.MapSpec `ebpf:"inbound_conns"`
	InternalDnsZones *ebpf.MapSpec `ebpf:"internal_dns_zones"`
	ProxyConfig      *ebpf.MapSpec `ebpf:"proxy_config"`
	ReportedIps      *ebpf.MapSpec `ebpf:"reported_ips"`
}

// firewallTcVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallTcVariableSpecs struct {
}

// firewallTcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFirewallTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallTcObjects struct {
	firewallTcPrograms
	firewallTcMaps
	firewallTcVariables
}

func (o *firewallTcObjects) Close() error {
	return _FirewallTcClose(
		&o.firewallTcPrograms,
		&o.firewallTcMaps,
	)
}

// firewallTcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFirewallTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallTcMaps struct {
	AllowedDomains   *ebpf.Map `ebpf:"allowed_domains"`
	AllowedIps       *ebpf.Map `ebpf:"allowed_ips"`
	AllowedWildcards *ebpf.Map `ebpf:"allowed_wildcards"`
	Events           *ebpf.Map `ebpf:"events"`
	InboundConns     *ebpf.Map `ebpf:"inbound_conns"`
	InternalDnsZones *ebpf.Map `ebpf:"internal_dns_zones"`
	ProxyConfig      *ebpf.Map `ebpf:"proxy_config"`
	ReportedIps      *ebpf.Map `ebpf:"reported_ips"`
}

func (m *firewallTcMaps) Close() error {
	return _FirewallTcClose(
		m.AllowedDomains,
		m.AllowedIps,
		m.AllowedWildcards,
		m.Events,
		m.InboundConns,
		m.InternalDnsZones,
		m.ProxyConfig,
		m.ReportedIps,
	)
}

// firewallTcVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFirewallTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallTcVariables struct {
}

// firewallTcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFirewallTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallTcPrograms struct {
	FirewallTcDnsIngress *ebpf.Program `ebpf:"firewall_tc_dns_ingress"`
	FirewallTcEgress     *ebpf.Program `ebpf:"firewall_tc_egress"`
}

func (p *firewallTcPrograms) Close() error {
	return _FirewallTcClose(
		p.FirewallTcDnsIngress,
		p.FirewallTcEgress,
	)
}

func _FirewallTcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed firewalltc_bpfeb.o
var _FirewallTcBytes []byte
